services:
  mlflow:
    build:
      context: .
      dockerfile: MLflow
    container_name: mlflow_toolbox
    env_file:
      - ./envs/mlflow.env
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - shared_network
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres_toolbox
    env_file:
      - ./envs/postgres.env
    ports:
      - "10100:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared_network
    restart: on-failure

  minio:
    image: minio/minio:latest
    container_name: minio_toolbox
    env_file:
      - ./envs/minio.env
    networks:
      - shared_network
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - ./envs/minio.env
    depends_on:
      - minio
    networks:
      - shared_network
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc config host add local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
      mc mb local/models || true &&
      echo 'Initial bucket created'"
    restart: "no"

  magic:
    command: mage start default_repo
    env_file:
      - ./envs/mage.env
    build:
      context: .
      dockerfile: MageAI
    container_name: mage_toolbox
    environment:
      USER_CODE_PATH: /home/src/default_repo
    ports:
      - 6789:6789
      - 8182:8182
    volumes:
      - ./mage/default_repo:/home/src/default_repo
    networks:
      - shared_network
    restart: on-failure:5

  mageapi:
    image: ghcr.io/sedimark/mageapi/mage-api:development
    depends_on:
      - magic
    env_file:
      - ./envs/mageapi.env
    container_name: mage_api_toolbox
    ports:
      - 8000:8000
      - 8182:8182
    networks:
      - shared_network
    restart: on-failure:5

  orchestrator:
    image: ghcr.io/sedimark/sedimark-orchestration-ui/orchestrator:development
    depends_on:
      - mageapi
      - mlflowapi
    env_file:
      - ./envs/orchestrator.env
    container_name: orchestrator_toolbox
    ports:
      - 3000:3000
    networks:
      - shared_network
    restart: on-failure:5

  mlflowapi:
    build:
      context: ./mlflow_api
    env_file:
      - ./envs/mlflowapi.env
    container_name: mlflowapi_toolbox
    depends_on:
      - mlflow
    ports:
      - 8001:8001
    networks:
      - shared_network
    restart: on-failure:5

networks:
  shared_network:
    external: true

volumes:
  minio-data:
    driver: local

  postgres-data:
    driver: local
