# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${STELLIO_APP_NAME}-kafka-data
  namespace: ${STELLIO_NAMESPACE}
spec:
  storageClassName: ${STORAGECLASS}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

