# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${STELLIO_APP_NAME}-kafka-config
  namespace: ${STELLIO_NAMESPACE}
  labels:
    app: ${STELLIO_APP_NAME}-kafka
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${STELLIO_APP_NAME}-kafka:9092,PLAINTEXT_HOST://localhost:29092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@${STELLIO_APP_NAME}-kafka:29093'
  KAFKA_LISTENERS: "CONTROLLER://${STELLIO_APP_NAME}-kafka:29093,PLAINTEXT://${STELLIO_APP_NAME}-kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092"
  KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
  CLUSTER_ID: "ZGE2MTQ4NDk4NGU3NDE2Mm"
---

