# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${STELLIO_APP_NAME}-postgres-config
  namespace: ${STELLIO_NAMESPACE}
data:
  POSTGRES_MULTIPLE_EXTENSIONS: "postgis,timescaledb,pgcrypto"
  ACCEPT_TIMESCALE_TUNING: "TRUE"
---

