apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${STELLIO_APP_NAME}-sub
  name: ${STELLIO_APP_NAME}-sub
  namespace: ${STELLIO_NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    app: ${STELLIO_APP_NAME}-sub
---

