apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${STELLIO_APP_NAME}-search
  name: search-service
  namespace: ${STELLIO_NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    app: ${STELLIO_APP_NAME}-search
---

