apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${STELLIO_APP_NAME}-api
  name: ${STELLIO_APP_NAME}-api
  namespace: ${STELLIO_NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: ${STELLIO_APP_NAME}-api
---

